worker_processes 1;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events { worker_connections 1024; }

http {
    include     /etc/nginx/mime.types;
    include /etc/nginx/proxy.conf;

    sendfile    on;
    server_names_hash_bucket_size 64;
    client_max_body_size 512m;
    server_tokens off;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    log_format  main  '$remote_addr - $remote_user - - [$time_local] "$request" '
    '$status $body_bytes_sent $request_time "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for"';

    upstream selectify-frontend {
        server host.docker.internal:3000;
    }

     upstream selectify-server {
        server host.docker.internal:3001;
     }

    upstream selectify-payment-grpc {
        server host.docker.internal:3002;
    }

    upstream selectify-payment {
        server host.docker.internal:3003;
    }

    upstream selectify-merchant {
        server host.docker.internal:3004;
    }

    add_header X-Frame-Options SAMEORIGIN always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "geolocation=()" always;
    add_header Vary Accept-Encoding;

     server {
        listen 80;
        listen [::]:80;
        server_name _;
        return 301 https://$host$request_uri;
     }

     server {
        listen          443 ssl;
        listen          [::]:443 ssl;
        http2 on;

        listen 443 quic reuseport;
        listen [::]:443 quic reuseport;
        ssl_protocols TLSv1.3;

        add_header Alt-Svc 'h3=":443"; ma=86400' always;

        server_name     selectify.alwis.dev;

        ssl_certificate     /etc/ssl/fullchain.pem;
        ssl_certificate_key /etc/ssl/privkey.pem;
        #add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload";

        access_log /var/log/nginx/access.log main;
        proxy_redirect     off;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Host $server_name;

        location /api/v1/pay {
          proxy_pass  http://selectify-payment;
        }

        location /api/v1/merchant {
          proxy_pass  http://selectify-merchant;
        }

        location /api/v1 {
         proxy_pass  http://selectify-server;
        }

        location /payment.v1.PaymentService {
          grpc_pass grpc://selectify-payment-grpc;
        }

#         # Next.js HMR websocket (dev) + app traffic
#         location /_next/webpack-hmr {
#           proxy_pass http://selectify-frontend;
#           proxy_http_version 1.1;
#           proxy_set_header Upgrade $http_upgrade;
#           proxy_set_header Connection $connection_upgrade;
#           proxy_set_header Host $host;
#           proxy_set_header X-Real-IP $remote_addr;
#           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#           proxy_set_header X-Forwarded-Host $server_name;
#           proxy_read_timeout 86400;
#         }

        location / {
          proxy_pass http://selectify-frontend;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $connection_upgrade;
          proxy_read_timeout 86400;
        }
     }
}