// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: payment-pkg/grpc-proto/payment/payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_payment_pkg_grpc_proto_payment_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_pkg_grpc_proto_payment_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_pkg_grpc_proto_payment_payment_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type Payment struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId           uint64                 `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Provider          string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderPaymentId string                 `protobuf:"bytes,4,opt,name=provider_payment_id,json=providerPaymentId,proto3" json:"provider_payment_id,omitempty"`
	ClientSecret      string                 `protobuf:"bytes,5,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Status            string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Amount            int64                  `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency          string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	FailureCode       string                 `protobuf:"bytes,9,opt,name=failure_code,json=failureCode,proto3" json:"failure_code,omitempty"`
	FailureMessage    string                 `protobuf:"bytes,10,opt,name=failure_message,json=failureMessage,proto3" json:"failure_message,omitempty"`
	CreatedAtUnix     int64                  `protobuf:"varint,11,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix     int64                  `protobuf:"varint,12,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	PaidAtUnix        int64                  `protobuf:"varint,13,opt,name=paid_at_unix,json=paidAtUnix,proto3" json:"paid_at_unix,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_payment_pkg_grpc_proto_payment_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_payment_pkg_grpc_proto_payment_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_payment_pkg_grpc_proto_payment_payment_proto_rawDescGZIP(), []int{1}
}

func (x *Payment) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Payment) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Payment) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Payment) GetProviderPaymentId() string {
	if x != nil {
		return x.ProviderPaymentId
	}
	return ""
}

func (x *Payment) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *Payment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Payment) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment) GetFailureCode() string {
	if x != nil {
		return x.FailureCode
	}
	return ""
}

func (x *Payment) GetFailureMessage() string {
	if x != nil {
		return x.FailureMessage
	}
	return ""
}

func (x *Payment) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *Payment) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *Payment) GetPaidAtUnix() int64 {
	if x != nil {
		return x.PaidAtUnix
	}
	return 0
}

type PaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_payment_pkg_grpc_proto_payment_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_pkg_grpc_proto_payment_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_pkg_grpc_proto_payment_payment_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

var File_payment_pkg_grpc_proto_payment_payment_proto protoreflect.FileDescriptor

const file_payment_pkg_grpc_proto_payment_payment_proto_rawDesc = "" +
	"\n" +
	",payment-pkg/grpc-proto/payment/payment.proto\x12\n" +
	"payment.v1\"+\n" +
	"\x0ePaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\"\xaf\x03\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x04R\aorderId\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12.\n" +
	"\x13provider_payment_id\x18\x04 \x01(\tR\x11providerPaymentId\x12#\n" +
	"\rclient_secret\x18\x05 \x01(\tR\fclientSecret\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x16\n" +
	"\x06amount\x18\a \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x12!\n" +
	"\ffailure_code\x18\t \x01(\tR\vfailureCode\x12'\n" +
	"\x0ffailure_message\x18\n" +
	" \x01(\tR\x0efailureMessage\x12&\n" +
	"\x0fcreated_at_unix\x18\v \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\f \x01(\x03R\rupdatedAtUnix\x12 \n" +
	"\fpaid_at_unix\x18\r \x01(\x03R\n" +
	"paidAtUnix\"@\n" +
	"\x0fPaymentResponse\x12-\n" +
	"\apayment\x18\x01 \x01(\v2\x13.payment.v1.PaymentR\apayment2Z\n" +
	"\x0ePaymentService\x12H\n" +
	"\rCreatePayment\x12\x1a.payment.v1.PaymentRequest\x1a\x1b.payment.v1.PaymentResponseB<Z:alwis.dev/selectify/payment-pkg/grpc-proto/payment;paymentb\x06proto3"

var (
	file_payment_pkg_grpc_proto_payment_payment_proto_rawDescOnce sync.Once
	file_payment_pkg_grpc_proto_payment_payment_proto_rawDescData []byte
)

func file_payment_pkg_grpc_proto_payment_payment_proto_rawDescGZIP() []byte {
	file_payment_pkg_grpc_proto_payment_payment_proto_rawDescOnce.Do(func() {
		file_payment_pkg_grpc_proto_payment_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_pkg_grpc_proto_payment_payment_proto_rawDesc), len(file_payment_pkg_grpc_proto_payment_payment_proto_rawDesc)))
	})
	return file_payment_pkg_grpc_proto_payment_payment_proto_rawDescData
}

var file_payment_pkg_grpc_proto_payment_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_payment_pkg_grpc_proto_payment_payment_proto_goTypes = []any{
	(*PaymentRequest)(nil),  // 0: payment.v1.PaymentRequest
	(*Payment)(nil),         // 1: payment.v1.Payment
	(*PaymentResponse)(nil), // 2: payment.v1.PaymentResponse
}
var file_payment_pkg_grpc_proto_payment_payment_proto_depIdxs = []int32{
	1, // 0: payment.v1.PaymentResponse.payment:type_name -> payment.v1.Payment
	0, // 1: payment.v1.PaymentService.CreatePayment:input_type -> payment.v1.PaymentRequest
	2, // 2: payment.v1.PaymentService.CreatePayment:output_type -> payment.v1.PaymentResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_payment_pkg_grpc_proto_payment_payment_proto_init() }
func file_payment_pkg_grpc_proto_payment_payment_proto_init() {
	if File_payment_pkg_grpc_proto_payment_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_pkg_grpc_proto_payment_payment_proto_rawDesc), len(file_payment_pkg_grpc_proto_payment_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_pkg_grpc_proto_payment_payment_proto_goTypes,
		DependencyIndexes: file_payment_pkg_grpc_proto_payment_payment_proto_depIdxs,
		MessageInfos:      file_payment_pkg_grpc_proto_payment_payment_proto_msgTypes,
	}.Build()
	File_payment_pkg_grpc_proto_payment_payment_proto = out.File
	file_payment_pkg_grpc_proto_payment_payment_proto_goTypes = nil
	file_payment_pkg_grpc_proto_payment_payment_proto_depIdxs = nil
}
